language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CXX=g++-4.8 CC=gcc-4.8
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - gcc-4.8
            - g++-4.8
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
            - libboost-serialization1.55-dev
            - libboost-test1.55-dev
            - libboost-regex1.55-dev
    - os: osx
      compiler: clang

install:
  - hg clone https://bitbucket.org/eigen/eigen/ -r 346ecdb
  - cd eigen
  - mkdir build && cd build
  - cmake ..
  - sudo make install

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake .. -DEIGEN3_INCLUDE_DIR=/usr/local/include/eigen3

after_failure:
  - cat $TRAVIS_BUILD_DIR/build/CMakeFiles/CMakeError.log

script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then make -j$(nproc); fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then make -j$(sysctl -n hw.ncpu); fi
  - make test
